<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiffPlex" Version="1.9.0" />
    <PackageReference Include="ICSharpCode.Decompiler" Version="10.0.1.8346" />
    <PackageReference Include="NuGet.Packaging" Version="7.3.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NuGetDiff.Core.Tests" />
  </ItemGroup>

</Project>
